#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Dict, Any, Tuple, Optional


def parse_gro(path: Path) -> Tuple[str, List[Dict[str, Any]], List[float]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if len(lines) < 3:
        raise SystemExit(f"Invalid GRO (too few lines): {path}")
    title = lines[0].rstrip("\n")
    try:
        natoms = int(lines[1].strip())
    except Exception:
        raise SystemExit(f"Invalid GRO atom count line: {path}")

    atom_lines = lines[2 : 2 + natoms]
    if len(atom_lines) != natoms:
        raise SystemExit(f"Invalid GRO atom lines count mismatch: {path}")

    box_line = lines[2 + natoms].strip()
    box = [float(v) for v in box_line.split()]
    if len(box) not in (3, 9):
        raise SystemExit(f"Invalid GRO box line (need 3 or 9 floats): {path}")

    recs: List[Dict[str, Any]] = []
    for idx, ln in enumerate(atom_lines, start=1):
        if len(ln) < 44:
            raise SystemExit(f"Invalid GRO atom line {idx} (too short) in {path}")
        resid = int(ln[0:5])
        resname = ln[5:10].strip()
        atomname = ln[10:15].strip()
        atomid = int(ln[15:20])

        rest = ln[20:].strip().split()
        if len(rest) < 3:
            raise SystemExit(f"Invalid GRO atom line {idx} (missing coords) in {path}")
        x, y, z = map(float, rest[:3])

        vx = vy = vz = None
        if len(rest) >= 6:
            vx, vy, vz = map(float, rest[3:6])

        recs.append(
            {
                "resid": resid,
                "resname": resname,
                "atomname": atomname,
                "atomid": atomid,
                "x": x,
                "y": y,
                "z": z,
                "vx": vx,
                "vy": vy,
                "vz": vz,
            }
        )

    return title, recs, box


def _gro_name5(s: str) -> str:
    s = (s or "").strip()
    return s[:5]


def gro_atom_line(rec: Dict[str, Any]) -> str:
    resid = int(rec["resid"]) % 100000
    atomid = int(rec["atomid"]) % 100000
    rn = _gro_name5(str(rec["resname"]))
    an = _gro_name5(str(rec["atomname"]))
    x, y, z = float(rec["x"]), float(rec["y"]), float(rec["z"])

    core = f"{resid:5d}{rn:<5}{an:>5}{atomid:5d}{x:8.3f}{y:8.3f}{z:8.3f}"
    vx, vy, vz = rec.get("vx"), rec.get("vy"), rec.get("vz")
    if vx is not None and vy is not None and vz is not None:
        core += f"{float(vx):8.4f}{float(vy):8.4f}{float(vz):8.4f}"
    return core + "\n"


def write_gro(path: Path, title: str, recs: List[Dict[str, Any]], box: List[float]) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write((title or "Generated by make_ref_gro.py") + "\n")
        f.write(f"{len(recs)}\n")
        for rec in recs:
            f.write(gro_atom_line(rec))
        f.write("".join(f"{v:10.5f}" for v in box) + "\n")


def read_ndx_group(ndx_path: Path, group: str) -> List[int]:
    """
    Read a GROMACS .ndx file and return 1-based atom indices from the given group.
    """
    target = group.strip()
    lines = ndx_path.read_text(encoding="utf-8").splitlines()

    in_group = False
    idxs: List[int] = []

    for ln in lines:
        s = ln.strip()
        if not s:
            continue
        if s.startswith("[") and s.endswith("]"):
            name = s[1:-1].strip()
            in_group = (name == target)
            continue
        if in_group:
            for tok in s.split():
                try:
                    idxs.append(int(tok))
                except ValueError:
                    pass

    if not idxs:
        raise SystemExit(f"Group [{target}] not found or empty in {ndx_path}")

    return sorted(set(idxs))


def main() -> None:
    ap = argparse.ArgumentParser(
        description="Create a per-iteration reference GRO for GROMACS -r: "
                    "use coord GRO as template, but overwrite FIXED atom coordinates from an initial ref GRO."
    )
    ap.add_argument("--coord", required=True, help="Current coordinates GRO (template, e.g. best.gro)")
    ap.add_argument("--ref", required=True, help="Initial reference GRO (coordinate donor for FIXED atoms, e.g. ref0.gro)")
    ap.add_argument("--ndx", required=True, help="Index file containing the FIXED group (1-based atom indices)")
    ap.add_argument("--group", required=True, help="Group name in .ndx (e.g. FIXED)")
    ap.add_argument("--out", required=True, help="Output reference GRO (e.g. ref.gro)")
    ap.add_argument("--strict-name-check", action="store_true",
                    help="Fail if (resid,resname,atomname) differs between coord and ref for any FIXED atom index.")
    args = ap.parse_args()

    coord_path = Path(args.coord).resolve()
    ref_path = Path(args.ref).resolve()
    ndx_path = Path(args.ndx).resolve()
    out_path = Path(args.out).resolve()

    _, coord_recs, coord_box = parse_gro(coord_path)
    _, ref_recs, _ = parse_gro(ref_path)

    fixed = read_ndx_group(ndx_path, args.group)

    # Overwrite coordinates for FIXED atoms
    for idx in fixed:
        i = idx - 1  # to 0-based
        if i < 0 or i >= len(coord_recs):
            raise SystemExit(f"FIXED atom index {idx} out of range for coord GRO (natoms={len(coord_recs)})")
        if i < 0 or i >= len(ref_recs):
            raise SystemExit(f"FIXED atom index {idx} out of range for ref GRO (natoms={len(ref_recs)})")

        if args.strict_name_check:
            c = coord_recs[i]
            r = ref_recs[i]
            if (c["resid"], c["resname"], c["atomname"]) != (r["resid"], r["resname"], r["atomname"]):
                raise SystemExit(
                    f"Name mismatch at atom {idx}:\n"
                    f"  coord: resid={c['resid']} resname={c['resname']} atomname={c['atomname']}\n"
                    f"  ref:   resid={r['resid']} resname={r['resname']} atomname={r['atomname']}\n"
                    f"Atom ordering likely changed; rebuild FIXED indices or adjust mapping strategy."
                )

        coord_recs[i]["x"] = ref_recs[i]["x"]
        coord_recs[i]["y"] = ref_recs[i]["y"]
        coord_recs[i]["z"] = ref_recs[i]["z"]

    title = f"Reference for -r (FIXED from {ref_path.name}, template {coord_path.name})"
    write_gro(out_path, title, coord_recs, coord_box)


if __name__ == "__main__":
    main()
